// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRG.Proof360.Integrations.Infrastructure.Persistence;

#nullable disable

namespace PRG.Proof360.Integrations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConnectorDbContext))]
    [Migration("20260717143545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PRG.Proof360.Integrations.Core.Integration.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalEntityType")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CanonicalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LatencyMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Core.Integration.ConnectorState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CircuitState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeadLetterCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InboxBacklogCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastCheckpoint")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSuccessfulSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutboxBacklogCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName", "ProviderInstanceId")
                        .IsUnique()
                        .HasDatabaseName("ux_connector_state_instance");

                    b.ToTable("connector_states", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Core.Integration.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CausationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("EventVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadEnvelope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderInstanceId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_inbox_event");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Core.Integration.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalEntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpectedCanonicalVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultReference")
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderInstanceId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_outbox_idempotency");

                    b.HasIndex("State", "NextAttemptAt");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Core.Integration.ProviderIdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalEntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CanonicalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalEntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAppliedVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderInstanceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0u);

                    b.HasKey("Id");

                    b.HasIndex("ProviderInstanceId", "CanonicalEntityType", "CanonicalId")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_canonical");

                    b.HasIndex("ProviderInstanceId", "ExternalEntityType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_external");

                    b.ToTable("provider_identity_links", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Domain.Canonical.Job", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<string>("AddressCity")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_city");

                    b.Property<string>("AddressPostal")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_postal");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_street");

                    b.Property<string>("AddressUnit")
                        .HasColumnType("TEXT")
                        .HasColumnName("address_unit");

                    b.Property<decimal?>("AiConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("AiJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_json");

                    b.Property<Guid?>("AssignedVendorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_vendor_id");

                    b.Property<bool>("ComplianceOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compliance_only");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_phone");

                    b.Property<string>("NotesScope")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes_scope");

                    b.Property<string>("Priority")
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("ServiceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Subcategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("subcategory");

                    b.Property<Guid?>("TranscriptId")
                        .HasColumnType("TEXT")
                        .HasColumnName("transcript_id");

                    b.Property<DateTimeOffset?>("WindowEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset?>("WindowStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("window_start");

                    b.HasKey("JobId");

                    b.HasIndex("AssignedVendorId");

                    b.HasIndex("Status");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Domain.Canonical.Transcript", b =>
                {
                    b.Property<Guid>("TranscriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("transcript_id");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset?>("CallEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("call_end");

                    b.Property<DateTimeOffset?>("CallStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("call_start");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("City");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("TEXT")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration");

                    b.Property<Guid?>("JobRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_ref");

                    b.Property<string>("RawText")
                        .HasColumnType("TEXT")
                        .HasColumnName("Raw_text");

                    b.Property<string>("Sentiment")
                        .HasColumnType("TEXT")
                        .HasColumnName("sentiment");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at");

                    b.Property<string>("Topics")
                        .HasColumnType("TEXT")
                        .HasColumnName("topics");

                    b.Property<Guid?>("VendorRef")
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor_ref");

                    b.HasKey("TranscriptId");

                    b.ToTable("transcripts", (string)null);
                });

            modelBuilder.Entity("PRG.Proof360.Integrations.Domain.Canonical.Vendor", b =>
                {
                    b.Property<Guid>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("vendor_id");

                    b.Property<decimal?>("AiConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_confidence");

                    b.Property<string>("ComplianceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("compliance_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("InsuranceCoverage")
                        .HasColumnType("TEXT")
                        .HasColumnName("insurance_coverage");

                    b.Property<DateOnly?>("InsuranceExpiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("insurance_expiry");

                    b.Property<string>("InsurancePolicy")
                        .HasColumnType("TEXT")
                        .HasColumnName("insurance_policy");

                    b.Property<DateOnly?>("LicenseExpiry")
                        .HasColumnType("TEXT")
                        .HasColumnName("license_expiry");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("license_number");

                    b.Property<string>("MissingItems")
                        .HasColumnType("TEXT")
                        .HasColumnName("missing_items");

                    b.Property<string>("Rationale")
                        .HasColumnType("TEXT")
                        .HasColumnName("rationale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("WcbNumber")
                        .HasColumnType("TEXT")
                        .HasColumnName("wcb_number");

                    b.HasKey("VendorId");

                    b.ToTable("vendors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
